apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    run: inventory
  ports:
  - name: 8080-tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer


